#ifndef FLUTTER_IPL_INCLUDE_CORE_FORMATS_H_
#define FLUTTER_IPL_INCLUDE_CORE_FORMATS_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum : int {
  IPL_WINDING_ORDER_CLOCKWISE = 0,
  IPL_WINDING_ORDER_COUNTER_CLOCKWISE = 1,
} ipl_winding_order_t;

typedef enum : int {
  IPL_STORAGE_MODE_HOST_VISIBLE = 0,
  IPL_STORAGE_MODE_DEVICE_PRIVATE = 1,
  IPL_STORAGE_MODE_DEVICE_TRANSIENT = 2,
} ipl_storage_mode_t;

typedef enum : uint8_t {
  IPL_PIXEL_FORMAT_UNKNOWN = 0,
  IPL_PIXEL_FORMAT_A8_UNORM_INT = 1,
  IPL_PIXEL_FORMAT_R8_UNORM_INT = 2,
  IPL_PIXEL_FORMAT_R8_G8_UNORM_INT = 3,
  IPL_PIXEL_FORMAT_R8_G8_B8_A8_UNORM_INT = 4,
  IPL_PIXEL_FORMAT_R8_G8_B8_A8_UNORM_INT_SRGB = 5,
  IPL_PIXEL_FORMAT_B8_G8_R8_A8_UNORM_INT = 6,
  IPL_PIXEL_FORMAT_B8_G8_R8_A8_UNORM_INT_SRGB = 7,
  IPL_PIXEL_FORMAT_R32_G32_B32_A32_FLOAT = 8,
  IPL_PIXEL_FORMAT_R16_G16_B16_A16_FLOAT = 9,
  IPL_PIXEL_FORMAT_B10_G10_R10_XR = 10,
  IPL_PIXEL_FORMAT_B10_G10_R10_XR_SRGB = 11,
  IPL_PIXEL_FORMAT_B10_G10_R10_A10_XR = 12,
  IPL_PIXEL_FORMAT_R32_FLOAT = 13,
  IPL_PIXEL_FORMAT_S8_UINT = 14,
  IPL_PIXEL_FORMAT_D24_UNORM_S8_UINT = 15,
  IPL_PIXEL_FORMAT_D32_FLOAT_S8_UINT = 16,
  IPL_PIXEL_FORMAT_BC1_RGBA_UNORM_INT = 17,
  IPL_PIXEL_FORMAT_BC1_RGBA_UNORM_INT_SRGB = 18,
  IPL_PIXEL_FORMAT_BC3_RGBA_UNORM_INT = 19,
  IPL_PIXEL_FORMAT_BC3_RGBA_UNORM_INT_SRGB = 20,
  IPL_PIXEL_FORMAT_BC5_RG_UNORM_INT = 21,
  IPL_PIXEL_FORMAT_BC7_RGBA_UNORM_INT = 22,
  IPL_PIXEL_FORMAT_BC7_RGBA_UNORM_INT_SRGB = 23,
  IPL_PIXEL_FORMAT_ETC2_RGB8_UNORM_INT = 24,
  IPL_PIXEL_FORMAT_ETC2_RGB8_UNORM_INT_SRGB = 25,
  IPL_PIXEL_FORMAT_ETC2_RGBA8_UNORM_INT = 26,
  IPL_PIXEL_FORMAT_ETC2_RGBA8_UNORM_INT_SRGB = 27,
  IPL_PIXEL_FORMAT_ASTC_4X4_LDR = 28,
  IPL_PIXEL_FORMAT_ASTC_4X4_LDR_SRGB = 29,
  IPL_PIXEL_FORMAT_ASTC_8X8_LDR = 30,
  IPL_PIXEL_FORMAT_ASTC_8X8_LDR_SRGB = 31,
  IPL_PIXEL_FORMAT_ASTC_4X4_HDR = 32,
  IPL_PIXEL_FORMAT_ASTC_8X8_HDR = 33,
} ipl_pixel_format_t;

typedef enum : int {
  IPL_BLEND_FACTOR_ZERO = 0,
  IPL_BLEND_FACTOR_ONE = 1,
  IPL_BLEND_FACTOR_SOURCE_COLOR = 2,
  IPL_BLEND_FACTOR_ONE_MINUS_SOURCE_COLOR = 3,
  IPL_BLEND_FACTOR_SOURCE_ALPHA = 4,
  IPL_BLEND_FACTOR_ONE_MINUS_SOURCE_ALPHA = 5,
  IPL_BLEND_FACTOR_DESTINATION_COLOR = 6,
  IPL_BLEND_FACTOR_ONE_MINUS_DESTINATION_COLOR = 7,
  IPL_BLEND_FACTOR_DESTINATION_ALPHA = 8,
  IPL_BLEND_FACTOR_ONE_MINUS_DESTINATION_ALPHA = 9,
  IPL_BLEND_FACTOR_SOURCE_ALPHA_SATURATED = 10,
  IPL_BLEND_FACTOR_BLEND_COLOR = 11,
  IPL_BLEND_FACTOR_ONE_MINUS_BLEND_COLOR = 12,
  IPL_BLEND_FACTOR_BLEND_ALPHA = 13,
  IPL_BLEND_FACTOR_ONE_MINUS_BLEND_ALPHA = 14,
} ipl_blend_factor_t;

typedef enum : int {
  IPL_BLEND_OPERATION_ADD = 0,
  IPL_BLEND_OPERATION_SUBTRACT = 1,
  IPL_BLEND_OPERATION_REVERSE_SUBTRACT = 2,
} ipl_blend_operation_t;

typedef enum : int {
  IPL_LOAD_ACTION_DONT_CARE = 0,
  IPL_LOAD_ACTION_LOAD = 1,
  IPL_LOAD_ACTION_CLEAR = 2,
} ipl_load_action_t;

typedef enum : int {
  IPL_STORE_ACTION_DONT_CARE = 0,
  IPL_STORE_ACTION_STORE = 1,
  IPL_STORE_ACTION_MULTISAMPLE_RESOLVE = 2,
  IPL_STORE_ACTION_STORE_AND_MULTISAMPLE_RESOLVE = 3,
} ipl_store_action_t;

typedef enum : int {
  IPL_TEXTURE_TYPE_2D = 0,
  IPL_TEXTURE_TYPE_2D_MULTISAMPLE = 1,
  IPL_TEXTURE_TYPE_CUBE = 2,
  IPL_TEXTURE_TYPE_EXTERNAL_OES = 3,
} ipl_texture_type_t;

typedef enum : uint8_t {
  IPL_SAMPLE_COUNT_1 = 1,
  IPL_SAMPLE_COUNT_4 = 4,
} ipl_sample_count_t;

typedef enum : int {
  IPL_TEXTURE_USAGE_UNKNOWN = 0,
  IPL_TEXTURE_USAGE_SHADER_READ = 1,
  IPL_TEXTURE_USAGE_SHADER_WRITE = 2,
  IPL_TEXTURE_USAGE_RENDER_TARGET = 4,
} ipl_texture_usage_t;

typedef enum : int {
  IPL_CULL_MODE_NONE = 0,
  IPL_CULL_MODE_FRONT_FACE = 1,
  IPL_CULL_MODE_BACK_FACE = 2,
} ipl_cull_mode_t;

typedef enum : uint8_t {
  IPL_INDEX_TYPE_UNKNOWN = 0,
  IPL_INDEX_TYPE_16BIT = 1,
  IPL_INDEX_TYPE_32BIT = 2,
  IPL_INDEX_TYPE_NONE = 3,
} ipl_index_type_t;

typedef enum : uint8_t {
  IPL_PRIMITIVE_TYPE_TRIANGLE = 0,
  IPL_PRIMITIVE_TYPE_TRIANGLE_STRIP = 1,
  IPL_PRIMITIVE_TYPE_LINE = 2,
  IPL_PRIMITIVE_TYPE_LINE_STRIP = 3,
  IPL_PRIMITIVE_TYPE_POINT = 4,
  IPL_PRIMITIVE_TYPE_TRIANGLE_FAN = 5,
} ipl_primitive_type_t;

typedef enum : int {
  IPL_POLYGON_MODE_FILL = 0,
  IPL_POLYGON_MODE_LINE = 1,
} ipl_polygon_mode_t;

#ifdef __cplusplus
}
#endif

#endif  // FLUTTER_IPL_INCLUDE_CORE_FORMATS_H_
